openapi: 3.0.0
info:
  title: Dating App API
  version: 1.0.0
servers:
  - url: https://d5dg37j92h7tg2f7sf87.o2p3jdjj.apigw.yandexcloud.net
x-yc-apigateway:
  cors:
    origin:
      - http://localhost:8081
      - http://localhost:19006
      - http://localhost:3000
      - https://hello-world-app-dusky.vercel.app
      - https://hello-world-ahse21m0a-sayans-projects-818ed142.vercel.app
      - https://weave-app-henna.vercel.app
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      - HEAD
      - OPTIONS
    allowedHeaders:
      - "*"
    exposedHeaders:
      - "*"
# -------------------------------------
paths:
  /ws:
    x-yc-apigateway-websocket-connect:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e7l76a7mc4mfhjvc6f
    x-yc-apigateway-websocket-disconnect:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e7l76a7mc4mfhjvc6f
    x-yc-apigateway-websocket-message:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e7l76a7mc4mfhjvc6f
  /register:
    post:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e7tedk8v6ng9d3u68f
      operationId: register
  /login:
    post:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e7tedk8v6ng9d3u68f
      operationId: login
  /telegram-login:
    post:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e7tedk8v6ng9d3u68f
      operationId: telegramLogin
  /me:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e7tedk8v6ng9d3u68f
      operationId: me
  /profile:
    post:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e7tedk8v6ng9d3u68f
      operationId: updateProfile
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e7l76a7mc4mfhjvc6f
      operationId: getprofile
  /matches:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e7l76a7mc4mfhjvc6f
      operationId: getmatches
  /chats:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e7l76a7mc4mfhjvc6f
      operationId: getchat
  /history:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e7l76a7mc4mfhjvc6f
      operationId: gethistory
  /like:
    post:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e7l76a7mc4mfhjvc6f
      operationId: getlike
  /dislike:
    post:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e7l76a7mc4mfhjvc6f
      operationId: dislike
  /discovery:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e7l76a7mc4mfhjvc6f
      operationId: getdiscovery
  /likes-you:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e7l76a7mc4mfhjvc6f
      operationId: getLikesYou
  /notifications/stats:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e7l76a7mc4mfhjvc6f
      operationId: getNotificationStats
  /mark-read:
    post:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e7l76a7mc4mfhjvc6f
      operationId: markAsRead
  /your-likes:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e7l76a7mc4mfhjvc6f
      operationId: getYourLikes
